apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      component: master
  template:
    metadata:
      labels:
        app: spark
        component: master
    spec:
      containers:
      - name: spark-master
        image: bitnami/spark
        ports:
        - containerPort: 7077
        env:
        - name: SPARK_MODE
          value: "master"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark
      component: worker
  template:
    metadata:
      labels:
        app: spark
        component: worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark
        ports:
        - containerPort: 8081
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark
    component: master
  ports:
    - protocol: TCP
      port: 7077
      targetPort: 7077

---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  selector:
    app: spark
    component: worker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
