apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  ports:
    - name: spark
      port: 7077
      targetPort: 7077
    - name: webui
      port: 8080
      targetPort: 8080
  selector:
      app: spark
      role: master
  type: ClusterIP
