apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7077 # Porta do Spark Master
            - containerPort: 8080 # UI do Spark Master
          env:
            - name: SPARK_MODE
              value: 'master'
            - name: SPARK_MASTER
              value: 'spark://spark-master:7077' # URL do Spark Master
