apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
      - name: spark-master
        image: my-spark-image
        imagePullPolicy: Never
        env:
        - name: SPARK_MODE
          value: "master"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"  # Definir o Spark Master URL para os Workers
        ports:
        - containerPort: 7077 # Comunicação entre Master e Workers
        - containerPort: 8080 # Interface Web
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: pv-tse-volume
          mountPath: /app/spark/data  # Caminho onde o volume será montado dentro do contêiner
      volumes:
      - name: pv-tse-volume
        persistentVolumeClaim:
          claimName: pvc-tse-claim
