apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  selector:
    app: spark
    role: master
  ports:
    - protocol: TCP
      port: 7077
      targetPort: 7077
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None # Não atribui um IP fixo, pois é um headless service
