apiVersion: v1
kind: Pod
metadata:
  name: extract-data
spec:
  restartPolicy: Never
  containers:
    - name: extract-data
      image: my-extract-data-image # build extract_data image first
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /app/data/raw
          name: raw-tse-volume
      resources:
        requests:
          memory: "500Mi"  # Quantidade mínima de memória
          cpu: "500m"      # Quantidade mínima de CPU (meio núcleo)
        limits:
          memory: "1Gi"    # Quantidade máxima de memória
          cpu: "1"         # Quantidade máxima de CPU (1 núcleo)
  volumes:
    - name: raw-tse-volume
      persistentVolumeClaim:
        claimName: raw-tse-claim
