apiVersion: v1
kind: Pod
metadata:
  name: streamlit-app
spec:
  containers:
    - name: streamlit
      image: my-streamlit-image
      imagePullPolicy: Never
      ports:
        - containerPort: 8501
      volumeMounts:
        - mountPath: /data
          name: gold-tse-volume
      resources:
        requests:
          memory: "512Mi"  # Quantidade mínima de memória
          cpu: "500m"      # Quantidade mínima de CPU (meio núcleo)
        limits:
          memory: "1Gi"    # Quantidade máxima de memória
          cpu: "1"         # Quantidade máxima de CPU (1 núcleo)
  volumes:
    - name: gold-tse-volume
      persistentVolumeClaim:
        claimName: gold-tse-claim
